name: Build when merged into Master

on:
  push:
    branches:
      - 'master'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=code::$(grep versionCode Stipop/build.gradle | awk '{print $2}')"
          echo "::set-output name=name::$(grep versionName Stipop/build.gradle | awk '{print $2}' | tr '"' ' ' | tr -d " ")"

      - name: Get tag name
        id: get_tag
        run: echo "::set-output name=name::v${{ steps.get_version.outputs.name }}"

      - name: Get release name
        id: get_release
        run: echo "::set-output name=name::v${{ steps.get_version.outputs.name }}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.name }}
          release_name: ${{ steps.get_release.outputs.name }}
          draft: false
          prerelease: false

      - name: Merge master into develop
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Stipop Github Bot
          SLACK_ICON_EMOJI: ':android1:'
          SLACK_CHANNEL: android_dev
          SLACK_TITLE: Merged into Master (Release)